### PR TITLE
fix(slack): deprecate unused properties from slack execution

### LINKED ISSUE #191: Fix ignored properties (like payload) on the SlackExecution task
### Describe the issue

Try running this flow in response to a failed flow -- there are a bunch of properties which are entirely ignored incl:
- `payload`
- `channel` - the channel of the webhook `url` is taken instead
- `username` - the name of the Slack app is used instead
- `iconUrl` - the icon of the Slack app is used instead

We should either **fix** or **remove** any `SlackExecution` properties that are currently ignored.

```yaml
id: sla_miss_alert
namespace: alerting

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: xxxxx
    executionId: "{{trigger.executionId}}"
    iconUrl: "https://avatars.githubusercontent.com/u/59033362?s=48"
    username: "SLA Miss Alert"
    channel: "#random"
    payload: |
      {
        "text": "SLA breached for flow {{trigger.namespace}}.{{trigger.flowId}} with ID {{trigger.executionId}}"
      } 

triggers:
  - id: alert_on_failure
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - FAILED
      - WARNING
      - CANCELLED
```

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Malaydewangan09**
### What changes are being made and why?
Deprecate unused properties for the `Slack` notification plugin, since they were not taken into account and can only be configured by Slack App configuration.

closes #191

### CODE REVIEW

**Review by AcevedoR — CHANGES_REQUESTED** [review]
If I remember correctly we tried to remove the channel property one day and that caused a prod outage for one of our customer, let me check

**Comment by AcevedoR** [comment]
https://github.com/kestra-io/plugin-notifications/commit/6dba6a62b378424edbe8ea444c66392a750a6c8c

**Comment by Ben8t** [comment]
Ok, from my understanding reading these:
- https://github.com/slackapi/java-slack-sdk/issues/699
- https://api.slack.com/legacy/custom-integrations/messaging/webhooks
Some Slack users can still be on legacy platform. Making the channel props still valuable and indeed breaking change if we remove it.
Probably why we aren't able to reproduce too

**Comment by Ben8t** [comment]
@Malaydewangan09 can you still mark these properties deprecated for now please

File: src/main/java/io/kestra/plugin/notifications/slack/SlackTemplate.java [hunk 1]
```diff
@@ -23,26 +23,6 @@
 @Getter
 @NoArgsConstructor
 public abstract class SlackTemplate extends SlackIncomingWebhook {
-    @Schema(
-        title = "Slack channel to send the message to"
-    )
```
Comment (Ben8t) [inline src/main/java/io/kestra/plugin/notifications/slack/SlackTemplate.java:28]: When you'll revert the removal to move to deprecation, can you add the following in the property description:

> This property works only with legacy webhook URLs, new Slack incoming webhook URLs are already tied to a specific channel.

File: src/main/java/io/kestra/plugin/notifications/slack/SlackTemplate.java [hunk 2]
```diff
@@ -24,23 +24,33 @@
 @NoArgsConstructor
 public abstract class SlackTemplate extends SlackIncomingWebhook {
     @Schema(
-        title = "Slack channel to send the message to"
+        title = "Slack channel to send the message to",
+        description = "This property works only with legacy webhook URLs, new Slack incoming webhook URLs are already tied to a specific channel." +
```
Comment (AcevedoR) [inline src/main/java/io/kestra/plugin/notifications/slack/SlackTemplate.java:28]:
```suggestion
        description = "This property works only with legacy webhook URLs, new Slack incoming webhook URLs are already tied to a specific channel. " +
```

File: src/main/java/io/kestra/plugin/notifications/slack/SlackTemplate.java [hunk 3]
```diff
@@ -24,23 +24,33 @@
 @NoArgsConstructor
 public abstract class SlackTemplate extends SlackIncomingWebhook {
     @Schema(
-        title = "Slack channel to send the message to"
+        title = "Slack channel to send the message to",
```
Comment (AcevedoR) [inline src/main/java/io/kestra/plugin/notifications/slack/SlackTemplate.java:27]:
```suggestion
        title = "Slack channel to send the message to.",
```

**Review by AcevedoR — APPROVED** [review]
